<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BTIPOCU" name="com.calculator.test.TCCalculator" tests="14" failures="0" timestamp="8 Dec 2018 21:34:14 GMT" time="99.525" errors="2">
  <testcase name="TCCalculator_Smoke005_VerifySevenMultOnePlusSixDivTwoMinusZero" time="7.111" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Smoke001_VerifyOnePlusTwo" time="6.771" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression005_VerifyMixOperation5" time="7.037" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression008_VerifyMixOperation8" time="7.687" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Smoke004_VerifyEightDivFour" time="7.695" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Smoke002_VerifyNineMinusThree" time="6.876" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression002_VerifyMixOperation2" time="7.492" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression004_VerifyMixOperation4" time="7.651" classname="com.calculator.test.TCCalculator">
    <error type="org.junit.ComparisonFailure" message="expected:&lt;[7]8&gt; but was:&lt;[56]8&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[7]8> but was:<[56]8>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.calculator.page.WebPage.verifyElementText(WebPage.java:48)
	at com.calculator.page.CalculatorPage.verifyResult(CalculatorPage.java:89)
	at com.calculator.test.TCCalculator.TCCalculator_Regression004_VerifyMixOperation4(TCCalculator.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TCCalculator_Regression004_VerifyMixOperation4 -->
  <testcase name="TCCalculator_Regression006_VerifyMixOperation6" time="6.696" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression001_VerifyMixOperation1" time="7.894" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression007_VerifyMixOperation7" time="6.077" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression009_VerifyMixOperation9" time="5.811" classname="com.calculator.test.TCCalculator"/>
  <testcase name="TCCalculator_Regression003_VerifyMixOperation3" time="6.884" classname="com.calculator.test.TCCalculator">
    <error type="org.junit.ComparisonFailure" message="expected:&lt;3[.193548387096774]&gt; but was:&lt;3[]&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<3[.193548387096774]> but was:<3[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.calculator.page.WebPage.verifyElementText(WebPage.java:48)
	at com.calculator.page.CalculatorPage.verifyResult(CalculatorPage.java:89)
	at com.calculator.test.TCCalculator.TCCalculator_Regression003_VerifyMixOperation3(TCCalculator.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TCCalculator_Regression003_VerifyMixOperation3 -->
  <testcase name="TCCalculator_Smoke003_VerifyFourMultiFive" time="7.843" classname="com.calculator.test.TCCalculator"/>
</testsuite> <!-- com.calculator.test.TCCalculator -->
